# Generated by Django 4.2.7 on 2023-12-05 02:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(default="Nombre x", max_length=100)),
                ("categoria", models.CharField(default="Categoria x", max_length=100)),
                ("codigo", models.IntegerField(max_length=100)),
                ("precio", models.IntegerField(max_length=100)),
            ],
        ),
    ]
