# Generated by Django 4.2.7 on 2023-12-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_productos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="codigo",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="producto",
            name="precio",
            field=models.IntegerField(),
        ),
    ]
